---

- name: update repo.
  shell: apt update

- name: Install required packages
  apt:
    name:
      - curl
      - git
      - wget
      - libnewt-dev
      - libssl-dev
      - libncurses5-dev
      - subversion
      - libsqlite3-dev
      - build-essential
      - libjansson-dev
      - libxml2-dev
      - uuid-dev