---
  - name: apt-https support
    shell: apt-get update && apt -y install ca-certificates curl gnupg lsb-release

  - name: Add Docker’s official GPG key
    shell: curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

  - name: Use the following command to set up the repository
    shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

  - name: install Docker
    shell: apt-get update && apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin